name: Daily Tweet Generation

on:
  schedule:
    # Runs twice daily at 8:30 AM and 4:30 PM IST (3:00 AM and 11:00 AM UTC)
    - cron: '0 3,11 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  generate-schedule:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Shorter timeout for schedule generation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate tweet schedule
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SESSION: ${{ github.event.schedule == '0 3 * * *' && 'morning' || 'evening' }}
        run: |
          max_attempts=3
          attempt=1
          
          while [ $attempt -le $max_attempts ]; do
            echo "Attempt $attempt of $max_attempts to generate schedule"
            if node generateSchedule.js; then
              echo "Schedule generated successfully"
              break
            else
              if [ $attempt -eq $max_attempts ]; then
                echo "Failed to generate schedule after $max_attempts attempts"
                exit 1
              fi
              echo "Waiting before retry..."
              sleep 30
              ((attempt++))
            fi
          done

      - name: Commit schedule
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add tweetSchedule.json
          git diff-index --quiet HEAD || (git commit -m "Generate tweet schedule" && git push)

  post-tweets:
    needs: generate-schedule
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 2 hours to allow for tweet intervals

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Post scheduled tweets
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          failed_tweets=0
          
          for i in {0..3}; do
            echo "Posting tweet $((i+1)) of 4..."
            
            # Pull latest changes before posting each tweet
            git pull origin main
            
            # Load schedule and get wait time
            if [ $i -lt 3 ]; then
              wait_time=$(node -e "
                const schedule = require('./tweetSchedule.json');
                const tweet = schedule.tweets[$i];
                const nextTweet = schedule.tweets[$i + 1];
                const waitMinutes = Math.floor((new Date(nextTweet.scheduledTime) - new Date(tweet.scheduledTime)) / 60000);
                console.log(waitMinutes * 60);  // Convert to seconds
              ")
            fi
            
            if ! node postScheduledTweet.js $i; then
              echo "Warning: Failed to post tweet $((i+1))"
              ((failed_tweets++))
            fi
            
            # Only continue if we haven't failed too many times
            if [ $failed_tweets -ge 3 ]; then
              echo "Too many failed tweets, stopping process"
              exit 1
            fi
            
            # Commit history after each successful tweet
            git add tweetHistory.json
            git diff-index --quiet HEAD || (git commit -m "Update tweet history for tweet $((i+1))" && git push)
            
            if [ $i -lt 3 ]; then
              echo "Waiting ${wait_time} seconds before next tweet..."
              sleep $wait_time
            fi
          done
          
          # If we completed with some failures but not too many, exit successfully
          if [ $failed_tweets -gt 0 ]; then
            echo "Completed with $failed_tweets failed tweets"
          fi
          exit 0

      - name: Final commit
        if: always()
        run: |
           git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
             git add tweetSchedule.json
              git diff-index --quiet HEAD || (git commit -m "Generate tweet schedule" && git push)
