name: Daily Tweet Generation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # 8:30 AM IST (Single trigger for morning session)
    - cron: '0 11 * * *' # 4:30 PM IST (Single trigger for evening session)

jobs:
  generate-tweets:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      SESSION: ${{ github.event.schedule == '0 3 * * *' && 'morning' || 'evening' }}
      BATCH_START_TIME: ${{ github.event.schedule == '0 3 * * *' && '0830' || '1630' }}

    strategy:
      matrix:
        tweet_number: [1, 2, 3, 4, 5]

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Calculate delay
        run: |
          RANDOM_MINUTES=$(( $RANDOM % 60 + ($matrix.tweet_number - 1) * 60 ))
          echo "DELAY_MINUTES=$RANDOM_MINUTES" >> $GITHUB_ENV
          
      - name: Wait for calculated delay
        run: |
          echo "Waiting for $DELAY_MINUTES minutes before tweet ${{ matrix.tweet_number }}"
          sleep $(( DELAY_MINUTES * 60 ))
          
      - name: Install dependencies
        run: npm install
        
      - name: Generate and post tweet
        run: node index.js
